name: giga_chad_starter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  analyzer: ^6.4.1
  collection: any
  async: any
  meta: ^1.11.0
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  curl_logger_dio_interceptor: ^1.0.0
  flutter_login: ^5.0.0
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  # BLoC
  flutter_bloc: 8.1.3

  # Networking
  dio: 5.3.3
  dart_jsonwebtoken: ^2.13.0

  # Persisting
  shared_preferences: 2.2.2

  # Logging
  stack_trace: ^1.11.0
  logging: 1.2.0

  # Utils
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path_provider: 2.1.0
  provider: ^6.1.2
  lottie: ^3.1.0
  hovering: ^1.0.4
  flutter_smart_dialog: ^4.9.5+1

  # Routing
  auto_route: ^9.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0

  # Utils
  flutter_gen_runner: 5.3.2
  freezed: ^2.4.7
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

